"""empty message

Revision ID: e6e3ef44885f
Revises: e1513480c5ff
Create Date: 2023-12-07 18:10:50.999672

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e6e3ef44885f'
down_revision = 'e1513480c5ff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('aboutMe', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('lastSeen', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('lastSeen')
        batch_op.drop_column('aboutMe')

    # ### end Alembic commands ###
